source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'omniauth'

gem "oa-openid"

# gem 'omniauth-google-oauth2'

# Gems required for automated documentation
gem 'yard'
gem 'redcarpet'

# Gem for attaching images to models
gem 'paperclip', '~> 3.0'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # Adding Twitter Bootstrap SASS gem 
  gem 'bootstrap-sass', '~> 2.3.1.0'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes

  gem 'tabulous', '1.3.0'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'execjs'

#gem for visual charts
gem 'lazy_high_charts'

# gem for age validations 
gem 'date_validator'

#gem used to select countries
gem 'country-select'


# group :nix do
#   gem 'therubyracer', :platforms => :ruby
# end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# devise gem used for authentication
gem 'devise','2.0'

gem "rspec-rails", :group => [:test, :development]
group :test do
  gem "factory_girl_rails"
  gem "capybara"
  gem "guard-rspec"
end

gem 'omniauth-twitter'